-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 27, 2020 at 04:36 PM
-- Server version: 5.7.24
-- PHP Version: 7.4.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `horoscopedb`
--

-- --------------------------------------------------------

--
-- Table structure for table `signs`
--

CREATE TABLE `signs` (
  `id` int(255) NOT NULL,
  `name` varchar(30) NOT NULL,
  `basicDescription` varchar(5000) NOT NULL,
  `famousPeople` varchar(3000) NOT NULL,
  `dailyHoroscope` varchar(3000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `signs`
--

INSERT INTO `signs` (`id`, `name`, `basicDescription`, `famousPeople`, `dailyHoroscope`) VALUES
(1, 'Ovan', 'Kao prvi znak u zodijaku, prisustvo ovna gotovo uvek označava početak nečega energičnog i burnog. Ne postoji puno stvari koje mogu da zaustave ovaj znak. Osobe rođene u znaku ovna konstantno su željne dinamike, brzine i takmičenja. Oni su uvek prvi u svemu- od posla do druženja.\n\nOvan je, zahvaljujući vladajućoj planeti - Marsu, jedan od najaktivnijih horoskopskih znakova. Sama simbolika ovna ukazuje na snagu ovog znaka kao pravog univerzumskog pobednika. Ljudi rođeni sa Suncem u ovnu predodređeni su da se ističu kroz traženje odgovora na lična i metafizička pitanja. To je najveća odlika ovakve inkarnacije.\n\nOvan je vatreni znak, kao lav i strelac. To znači da je u njihovoj prirodi da preduzimaju akcije, ponekad i pre nego što o tome dobro razmisle. Njihov vatreni vladar utiče na njihove odlične organizacione sposobnosti, pa ćete retko sresti ovna koji ne voli da završava više stvari odjednom, često i pre pauze za ručak! Izazovi se uvećavaju kada su nestrpljivi, agresivni i iskaljuju bes na drugima. Zbog toga, ovnovi bi mogli da se pozabave nekim tehnikama za smanjenje stresa,a za njih bi to bilo vrlo korisno.\n\nOvan vlada glavom i u njegovoj je prirodi da zaštiti misli kao fizičku sigurnost, više nego drugi znaci. Ovan tako može na lak način da pređe iz sfere misli na konkretnu akciju, što ga čini odličnim inicijatorom koji uči da usmeri svoju energiju na najproduktivniji način.\n\nOni su prirodno hrabri i retko se plaše pokušaja i rizika. Ali pošto Mars, njihov samouvereni vladar, želi da se kroz život kreće brzo, važno je da osiguraju svoju fizičku sigurnost, jer se mogu povrediti. Pa bi zato bilo dobro da nose kacigu dok voze bicikl ili da vežbaju sporije dok ne ojačaju.\n\nKako ovaj znak poseduje mladalačku snagu i energiju, bez obzira na godine, verovatno će izvršavati zadatke u rekordnom vremenu. Usklađivanjem sa samim sobom mogli bi postići najbolje rezultate.', 'Miodrag Petrović Čkalja\nMilutin Mima Karadžić\nMomo Kapor\nSrđan Todorović\n', 'Izluđuju vas dešavanja vezana za vaše radno mesto. Bilo da ste nezadovoljni finansijama ili kolektivom, danas morate da razmišljate u pravcu promena. Definitivno je da aktuelna situacija više nije podnošljiva. Najbitnije je da u celoj priči zadržite unutrašnji mir. Jedan prijatelj ima tajne koje će danas izaći na videlo. Pored svega, budite mu podrška.'),
(2, 'Bik', 'Snažan i pouzdan, bik je prvi kada dođe do ubiranja plodova vrednog rada. Ljubitelji su svega što je dobro i lepo i veoma često će biti okruženi materijalnim zadovoljstvima. Osobe rođene u znaku bika su veoma senzualne i taktilne. Dodir im je veoma važan kako u poslu tako i u romansi. Stabilan i konzervativan, bik je među najpouzdanijim znakovima zodijaka. Tvrdoglavost je osobina koja ga tera da stvari istera do kraja, kako bi sve bilo po standardima. Veoma su kreativni i uživaće u činjenici da prave stvari sopstvenim rukama.\n\nBik po samom svom nazivu ukazuje na pravu prirodu ovog znaka. Kao zemljani znak, on je opterećen svojom sigurnošću, pa samim tim i zaštitom kuće i porodice od negativnih uticaja. Oni su odlični u stvaranju novca i imaju tendenciju da svojim idejema i planovima najefektivnije zarade, štede i investiraju novac.\n\nBikovi su često poznati po svojoj tvrdoglavosti, ali se to takođe može protumačiti kao potpuna posvećenost izvršenju zadataka. Jednom kada donesu odluku, retko skreću sa ucrtanog puta, ljubavne veze ili posla. To ih čini odličnim radnicima, jer ostaju dugo da rade dok god ne završe posao kako treba i odličnim prijateljima, jer su uvek tu, bez obzira na iskušenja i turbulencije u životu.\n\nBika vodi planeta Venera, koja reprezentuje ljubav, privlačnost, lepotu i kreativnost. Tako, je u prirodi Bika da bude odličan kuvar, zabavljač i umetnik. On je odan, ponekad i previše, i ne voli iznenadne i neželjene promene koje će pokvariti život koji je brižljivo kreirao za sebe.\n\nDeo tela koji reprezentuje Bika je vrat i grlo. To znači da bi Bik trebalo da povede računa o ovim oblastima, više nego drugi znaci i nauči da kaže kada je potrebno, a ne da blokira energiju u ovom delu tela i tako prouzrokuje zdravstvene probleme.\n\nBik je jedan od znakova na kojeg najviše možete računati. Iako neki mogu imati veoma konzervativne poglede na svet ili biti prezaljubljeni u novac i bogatstvo, oni imaju sposobnost da unesu praktični glas razuma u bilo koju haotičnu i nezdravu situaciju. Izazovi rastu kada Bik mora da se suoči sa nestalnošću ili činjenicom da se životne stvari kreću, protiču. Ukoliko nauči kako da se prepusti to bi moglo da mu donese najveću životnu sreću.', 'Dragoljub Draža Mihailović\nNikola Simić\nMeša Selimović\nDesanka Maksimović\nLaza Lazarević', 'Ako ste od skoro otkrili da posedujete neki talenat ili pronašli zadovoljstvo u novom hobiju, danas ćete imati želju u potpunosti da mu se posvetite. Došlo je vreme da ugodite sebi i nemojte da se obazirete na tuđe mišljenje. Finansijska situacija je i više nego zadovoljavajuća. Razmislite o obnovi garderobe ili kupovini nekih aksesoara.'),
(3, 'Blizanci', 'Promenljivost je prava reč za ovaj dvostruki znak. Izražajan i oštrouman , blizanac predstavlja dve različite strane ličnosti i nikada nećete biti sigurni sa kojom ćete se suočiti. Sa jedne strane blizanac može biti društven, komunikativan i spreman za zabavu dok je sa druge ovaj vazdušni znak zamišljen, ozbiljan, nemiran pa čak i neodlučan. Oba blizanca su sposobna da se dobro prilagode životnom okruženju, zbog čega je divno poznavati ih. Ništa nije dosadno kada su blizanci u glavnoj ulozi.\n\nKao vazdušni znak, blizanac je zaokupljen svim aspektima uma. Kao i drugi vazdušni znaci vaga i vodolija, blizanci imaju potrebu da koriste svoj um ne samo za ideje, nego i istraživanje sveta oko njih. Blizanac mora sebi da postavlja životno komplikovana pitanja da bi se razvijao i rastao.\n\nBlizanac je vođen planetom Merkur koja prezentuje komunikacije, pisanje i učenje drugih. Ova planeta se brzo kreće, što ponekad znači da je blizančeva pažnja veoma kratkog daha. Zaljubljeni su u reči i deje, pa morate staviti prst na čelo ako želite da održite korak sa tako radoznalim znakom! Skoro sve o svetu ih fasicnira i imaju osećaj kao da nema dovoljno vremena da iskuse sve što žele da vide. To ih čini odličnim umetnicima, piscima i novinarima.\n\nZnak blizanac znači da ponekad ljudi rođeni u ovom znaku imaju osećaj da im druga polovina nedostaje, pa je zauvek traže u prijateljima, mentorima ili saradnicima.\n\nDeo tela koji je u vezi sa ovim znakom su ruke, ramena i pluća. Blizanac po svojoj prirodi mora da obrati više pažnje na ove oblasti i da se postara da ih zaštiti u ovakvoj inkarnaciji. Pluća bi trebalo da su otvorena i slobodna da bi blizanac mogao da uživa u srećnom i dugom životu.\n\nZato što je blizanac tako svestran i radoznao, važno je da ne preduzima više nego što može. Naravno, on želi da iskusi sve što je tamo negde, ali to ne može činiti ako je bolestan i umoran. Izazovi nastaju kada blizanac postaje dvoličan ili ne može da ostane odan jednoj ideji, uverenju ili osobi. Umesto što rasipa energiju bolje je da ostane skoncentrisan na najvažnije stvari.', 'Jelisaveta Seka Sablić\nAnica Dobra\nZdravko Čolić\nPaja Jovanović\nDragan Nikolić\nNovak Đoković', 'Danas biste mogli da dođete do nekih novih informacija koje se tiču vaše prošlosti. Neće vam biti prijatno kada shvatite da je jedna osoba u koju ste imali poverenja i sa njom delili tajne, iznela u javnost vašu intimu. Ne dozvolite sebi da očajavate, nego istog momenta stupite u akciju. Obavite jedan iskren razgovor i zatvorite vrata ovog prijateljstva.'),
(4, 'Rak', 'Duboko intuitivan i sentimentalan, rak može biti jedan od najizazovnijih znakova zodijaka za upoznavanje. Emocije raka su izuzetno jake, a kada je reč o porodici i kući ništa im nije važnije. Saosećajan i empatičan, rak je veoma privržen ljudima koji ga okružuju. Za osobe rođene u znaku raka odanost je ključna reč.\n\nZa raka, porodica i kuća su ključ. Vodeni znak, kao škorpija i ribe, upravlja prvo osećanjima i potrebno mu je da se oseća sigurno pre nego Vas pusti blizu, kako bi izrazio svoja najdublja osećanja. Često su to empatični ljudi, sposobni da saosećaju sa Vaši bolom ili patnjom celog sveta.\n\nVladajuća planeta Mesec navodi raka da se čudno ponaša prema ljudima koji su skloni direktnom pristupu. Ali rak ne pokušava da bude manipulator. On samo ima potrebu da Vas veliča pre nego što se oseti dovoljno sigurano, kako ne bi rizikovao vaše odbijanje. Mesec mu daje sposobnost psihičkog proboja koji rak može razviti tokom života, ako tako izabere.\n\nZa rakove je karakteristično kretanje na sve strane. Ovi ljudi su u stanju da izokola iznose svoj problem, pre nego pređu na stvar, što ih čini teške za spoznati. Zahteva se dodatna pažnja dok iznose priču na svoj način. Važno je ne prekidati ih, jer postoji mogućnost da se u svoj oklop uvuku zauvek. Ukoliko žele da ostanu sigurni i zdravi tokom života, trebalo bi da se više pozabave organima u predelu stomaka i grudi. Problemi sa varenjem se često javljaju u starosti.\n\nProblem nastaje kada je rak suviše osetljiv, za svoje dobro, ili pokušava da preuzme sve probleme ovog sveta. Umerena saosećajnost je jedna stvar, ali biti toliko odan nekoj osobi da gubiš sebe, nije zdravo. Težiti nekoj sredini i ravnoteži u svim stvarima pomoćiće mu da dostigne najbolje rezultate za sebe i za ljude kojima želi da pomogne. Pored vode se osećaju najudobnije i to im pomaže da prodru u prošlost da se ne bi nepotrebno vezivali. ', 'Ljubivoje Ršumović\nNikola Đuričko\nĐura Jakšić\nNikola Tesla\nMirjana Bobić Mojsilović', 'Vaš krug prijatelja se menja. Moguće i previše brzo za vaš ukus. Neke od dragih osoba bi mogle da se odsele iz vaše blizine, a druge su verovatno zauzete nekim novim prijateljstvima. Pa ipak, vi se i pored svega veoma dobro držite. Najbitnije je da ne zaboravite da uvek u životu date prednost kvalitetu naspram kvantiteta.'),
(5, 'Lav', 'Svi su obavešteni kada moćni lav ulazi u centar pažnje. Dobar razlog za privlačnost je ključna reč za dramatičnog, kreativnog i društvenog lava. Vatrenom i samouverenom, lavu je izuzetno teško odoleti. Lav će doneti puno toga dobrog bilo da se radi o napornom poslu ili vremenu provedenom sa prijateljima i porodicom.\n\nLav je vatreni znak koji voli život i od njega očekuje da se dobro zabavlja. Kao i ostali vatreni znaci, strelac i ovan i ovaj je spreman da koristi svoj um za rešavanje najkomplikovanijih problema i preuzme inicijativu za rešavanje raznih zamršenih situacija. Lav to shvata kao način da se najbolje izrazi.\n\nSunce je vladar lava zato obožava sunce u svim oblicima što je i metaforički izraz stanja njegovog ega. To može biti zdravo sa jedne strane, jer on lako traži ono što mu treba. Sa druge strane, problematično je kada lav ignoriše probleme i potrebe drugih kako bi ispunio svoje želje. Ljudi rođeni u ovom znaku moraju biti svesni svog okruženja.\n\nLav ima specifičnu snagu i status \"kralja džungle\". Često ima monogo prijatelja jer je veoma darežljiv i odan. Tako samouveren i privlačan u stanju je da ujedini više grupa ljudi u svakoj prilici.\n\nLav mora pripaziti na srce i kičmu. Srce je najvažnije za funkcionisanje jednog lava, pa se tako savetuju redovni pregledi kako bi održao dobro zdravlje. Kontrolisane vežbe se takođe preporučuju.\n\nProblemi sa Lavom mogu nastati kada postane prezaljubljen u svoja dostignuća. On je arogantan, nefleksibilan i lenj jer pretpostavlja da će neko drugi počistiti za njim. Zdrav smisao za humor može učiniti lakšim saradnju sa drugim ljudima.', 'Zoran Đinđić\nJovan Skerlić\nDanilo Bata Stojković\nSloboda Mićalović\nAleksandar Đorđević\nŽeljko Joksimović', 'Iako vam se isprva bude činilo da je ovo idealan dan za posao, naićićete na prepreke kakve niste ni sanjali. Stvari se ne odvijaju ni na željeni način, ni željenim tempom. Međuljudski odnosi su takođe narušeni. Bez ikakvih razloga ste inicijator svađa i nesporazuma. Za vas je najbolje da danas ostanete kući i posvetite se nekim aktivnostima koje ne iziskuju veći mentalni napor.'),
(6, 'Devica', 'Sa konstantnim obraćanjem pažnje na detalje, devica je znak u zodijaku koji je najviše posvećen služenju. Njihov dubok smisao za humanost čini ih najbrižnijim znakom zodijaka, a metodičan pristup životu obezbeđuje da ništa ne bude prepušteno slučaju. Devica je često nežna ali i oprezna, prvo korak u nazad da se stvar analizira dobro pa tek onda korak napred.\n\nDevica je kao bik i jarac zemljani znak, a oni vole konzervativne i organizovane stvari, kao i one koje od njih zavise. To su znaci koji vole život sređen po fasiklama, čak i ako su najneuredniji na svetu, ciljeve i snove postavljaju na strogo određena mesta u glavi. Pitajte ih i naučićete mnogo o ovom znaku.\n\nPošto je Merkur vladajuća planeta device ona ima dobro razvijen osećaj za govor i pisanje, kao i za sve ostale oblike komunikacije. Kako su prirodno metodični u stanju su da dopru u srž svake haotične situacije i odbace sve što je nepotrebno u nečijem govoru ili izrazu. Merkur im daje umešnost sa rečima pa se tako mnogi odluče za spisateljski ili novinarski poziv.\n\nDevica je često pogrešno protumačena, zbog simbolike imena ovog znaka. Ona sve doživljava po prvi put. Život koristi da otkriva iako izgleda nevino, ona otkrića koristi da bi udovoljila drugima. Tako je neretko da odabere poziv koji se odnosi na brigu o drugima, nešto kao posao negovatelja.\n\nKako je nervni sistem povezan sa ovim znakom, trebalo bi da se zaštiti od prekomernog stresa, praktikuje uravnotežene dijete, uključi u neke programe telesnih vežbi, dovoljno spava i unosi dovoljno tečnosti. Za devicu je redovan lekarski pregled način da osigura dug i plodonosan život.\n\nKada mnogo brine i suviše kritikuje ljude oko sebe stvara probleme. Ovaj znak je možda i nepravedno poznat po sitničavosti pa je važno da gaji toleranciju i nauči da traži pomoć kada je neophodno.', 'Dejan Savićević\nSergej Trifunović\nNikola Kojo\nSonja Savić\nPatrijarh Pavle Stojčević\nNikola Grbić\n', 'Ako vaš posao zahteva dodatna istraživanja ili edukaciju, ovo je pravi dan za to. Mentalno i fizički ste spremni na sve izazove koje sa sobom donose sati neprekidnog rada. Uveče, obavezno uhvatite momenat za porodicu ili bliske prijatelje. Odlazak u restoran će biti ono što će zaokružiti vaš dan i učiniti vas u potpunosti ispunjenim.'),
(7, 'Vaga', '\"Ja balansiram\" je ključna rečenica za ovaj znak, kad dođe do toga da sve treba držati pod kontrolom, vaga preuzima glavnu ulogu.. Miroljubiv i pravičan, ovaj znak mrzi da bude sam. Partnerstvo je veoma važno za vagu, posebno ono koje je na ličnom nivou. Sa svojim pobedničkim mentalitetom i kooperativnošću nisu skloni da budu dugo sami.\n\nVaga je vazdušni znak, izraženog intelekta i pronicljivog uma. U prirodi joj je da je inspirišu interesantne knjige, nesavladive diskusije i zanimljivi ljudi što joj rasteruje dosadu.\n\nVladajuća planeta Vage je ljubitelj lepih stvari - Venera, pa je kvalitet uvek važniji od kvantiteta za osobe u ovom znaku. Okružene su umetnošću, muzikom i prelepim mestima kako bi mogle da dostignu svoj puni potencijal. Pošto su po prirodi kooperativne, vrlo često rade sa drugima na kreativnim projektima.\n\nVagu fascinira ravnoteža i simetrija. Često su to osobe koje cene ravnopravnost, ne podnose nepravdu gde god ona bila i čine sve da je otklone. Nisu skloni suočavanju bez razloga i više vole da sačuvaju mir, gde je to moguće. Baš kao što su potrebna dva predmeta za ravnotežu tako i vage češće biraju da su u grupi ili paru, nego da su sami.\n\nVaga je povezana sa bubrezima koji su filter u izlučivanju neptrebnih materija iz organizma. Zato je važno da uzimaju dovoljno tečnosti, što smanjuje pritisak na bubrege i poboljšava opšte zdravstveno stanje. Periodični pregledi bubrega i mokraćnih kanala su važni kako bi im telo pravilno funkcionisalo.\n\nNajveći problem za vage je kada su prinuđene da biraju stranu. Ponekad provedu previše vremena u spoznaji i argumentaciji svake strane pa zaborave da uopšte imaju svoje mišljenje. Često se i rasplinu u svojoj neodlučnosti. Nije retko videti da Vage polude u donošenju odluka kada se uključi još koji argument ili mišljenje. Ključ je naravno u toj \"svetoj\" ravnoteži kojoj toliko teže.', 'Mihailo Lalić\nBranislav Nušić\nDragan Bjelogrlić\nMilorad Pavić\nNemanja Vidić\nIvo Andrić\nMihajlo Pupin\nMija Aleksić\nNadežda Petrović\nMilan Rakić', 'Danas biste mogli da se osećate uhvaćeni između želje da ostvarite jedan cilj, najverovatnije finansijski i želje da se posvetite nekim porodičnim stvarima. S obzirom da ste u dobrom raspoloženju i imate dovoljno energije, mogli biste da postignete obe stvari. Prijatelji od poverenja vam danas mogu biti od velike pomoći. Pratite razvoj situacije i uspećete sve što poželite.'),
(8, 'Škorpija', 'Pod kontrolom, dobar eksterijer duboko utiče na škorpije. Strastven, prodoran i odlučan istraživaće sve dok ne dođe do istine. Možda neće puno izražavati I pokazivati emocije, ali budite sigurni da se ispod površine dešavaju velike stvari. Odličan lider, osoba rođena u znaku škorpije je uvek svesna situacije, takođe se posebno ističe u snalažljivosti.\n\nŠkorpija je vodeni znak, kao riba i rak i živi za to da iskusi i izrazi emocije. Iako su osećanja veoma važna za škorpiju one ih iskazuju drugačije nego drugi vodeni znaci, češće skrivene u grudima. U svakom slučaju možete biti sigurni da će škorpija čuvati vaše tajne, kakve god one bile.\n\nPluton je planeta transformacija i promena i vladar ovog znaka. Kako se ova planeta sporo kreće otud škorpije karakteriše smireno i \"cool\" ponašanje, a prepoznaćete ih po odlučnoj i mistreioznoj pojavi. Ljudi često kažu da su Škorpije žestoke, verovatno zato što dobro razumeju pravila univerzuma. Neke škorpije mogu izgledati starije nego što zapravo jesu, tokom čitavog života. Odlični su lideri jer su veoma posvećeni onome što rade. U njihovoj prirodi je da stvore širok spektar promena svojim poletnim i probojnim idejama.\n\nDeo tela koji je u vezi sa ovim znakom je reproduktivni sistem. Zato su škorpije povezane sa seksom, strašću i željom, pa bi trebalo da se intenzivnije pozabave ovim delom tela kako bi očuvali zdravlje i snagu. Škorpije mogu promeniti svoje zdravstveno stanje odlučnošću i jakom voljom.\n\nIzazvane škorpije stvaraju probleme. Kako mrze vrdanja i neiskrenost u stanju su da budu veoma ljubomorne i nepoverljive, pa je od velike važnosti da nauče kako da lakše prihvate različita ljudska ponašanja. Hrabri su i zbog toga imaju puno prijatelja. Ukoliko se potrude da ne budu tako tajnoviti i podele osećanja i želje sa drugima, učvrstiće svoja prijateljstva. Toliko se toga dešava ispod površine prosečne škorpije da vam za otkrivanje svega neće biti dovoljan jedan život.', 'Miloš Crnjanski\nVuk Stefanović Karadzić\nPetar Petrović Njegoš\nAna Ivanović\nLjubiša Samardžić\nToma Zdravković\nBora Đorđević', 'Ako se danas nađete u većem krugu ljudi, najverovatnije poznanika, nemojte da se iznenadite kada primetite da su oni uglavnom raspoloženi za ogovaranja i površne razgovore. Na vreme se zapitajte da li iskreno uživate u ovakvim pričama. Jedan prijatelj iz vaše rane mladosti sa kojim ste još uvek u kontaktu, prolazi kroz turbulentan period. Budite mu od koristi.'),
(9, 'Strelac', 'Radoznao i energičan, Strelac je najveći putnik među znakovima zodijaka. Njihov filozofski pogled otvorenog uma motiviše ih da lutaju daleko i široko u potrazi za smislom života. Kao neko ko je ekstrovertan, optimista i entuzijasta teško ga je zadržati na zemlji. Strelac voli promene, u stvari promena je od suštinskog značaja da bi se osećao dobro.\n\nVatreni znak - strelac svoje misli pretvara u konkretne akcije i u stanju je da \"hoda bos po trnju\" da bi ostvario svoje ciljeve. Kao i ostali vatreni znaci on ima potrebu da je stalno u kontaktu sa svetom da bi iskusio što je više moguće. Nije mu u prirodi da sedi kod kuće i čeka da mu se nešto desi. Ako je potrebno da se nešto desi, on će to inicirati.\n\nVladajuća planeta strelca je Jupiter, najveća planeta zodijaka. Kako je Jupiter pokretač sudbinske sreće, nije ni čudo što je strelcima sreća uvek naklonjena. Uticaj Jupitera je jak na polju stvaranja i širenja, pa je za strelca važno da mu obim struka ne postane jedina stvar koja se širi tokom životnog veka. Njegov entuzijazam nema granice, pa zato poseduje odličan smisao za humor i izraženu radoznalost.\n\nDelovi tela u vezi sa Strelcem su butine i kukovi, pa je za njega vrlo važno da uloži dodatni napor i povede računa o organima u toj oblasti. Zato što voli prirodu, naročito kampovanje i pešačenje, mora obratiti pažnju da ne povredi ove delove tela. On će biti srećan dokle god je u stanju da istražuje, pa bi umerene telesne vežbe pospešile njegovo zdravstveno stanje i dovele ga u formu da neometano traga.\n\nProblem sa strelcima nastaje kada mu ostavite potpuno odrešene ruke. Pod uticajem Jupitera njima sloboda predstavlja najveće blago, jer samo tako neometano mogu da putuju i istražuju različite kulture i filozofije. Zbog svoje iskrenosti, strelci su često nestrpljivi i netaktični kada treba nešto da kažu ili urade, pa je važno da nauče da se izraze na tolerantan i društveno prihvatljiv način.', 'Svetlana Bojković\nJasna Šekarić\nJovan Jovanović Zmaj\nEmir Kusturica\nDražen Dalipagić\nDušan Radović\nStevan Sremac\nMileva Marić', 'Vi ste neko ko ozbiljno shvata svoju profesiju, ali u poslednjih nekoliko dana nema vremena za ostale aspekte života. Danas ne bi bilo loše da odete na zasluženi odmor. Nema razloga za brigu - ne morate da budete neko ko stalno strepi od razvoja situacije i budućnosti. Za sada se opustite i odvojite vreme za stvari koje vas ispunjavaju - hobije, prijatelje i porodicu.'),
(10, 'Jarac', 'Kada su u pitanju profesionalnost i tradicionalne vrednosti, jarac je prvi. Ovaj praktičan znak voli da se pozabavi životom na najkonvencionalniji način. Smatra se najozbiljnijim znakom zodijaka koji prirodno poseduje nezavisnost koja mu omogućava značajan napredak kako na ličnom planu tako i na poslovnom.\n\nJarac je zemljani znak preopterećen sigurnošću. Kao i za ostale zemljane znake bika i devicu, za Jarca su najveće životne vrednosti tradicija, porodica i sve ostale stvari koji će činiti život disciplinovanim i u nekom redu. Jarac je majstor u samokontroli i ima potencijala da bude odličan lider ili menadžer dokle god je u sferi biznisa.\n\nSaturn je vladajuća planeta jarca i planeta poznata po zabranama i ograničenjima. Ova planeta pomaže da se sve apstraktne ideje konkretizuju i sprovedu u delo, zato jarac preuzima odgovornost i navodi nas da se ponašamo odraslo. Uticaj Saturna čini jarčeve praktičnim, pa je neretko da štede novac za budućnost i ulažu težak rad da bi ostvarili svoje planove. Majstori su u povlačenju konaca i dokazivanju da su samo oni u pravu.\n\nJarac ili koza, dovoljno objašnjava koliko ovaj znak ume da bude tvrdoglav. U svojim namerama su u stanju da se popnu i na najvišu planinu. Trude se da samo svojim iskustvom stignu na vrh, ali njihova ozbiljnost i nezavisnost čini ih preduzimljivim čega god se late.\n\nSlabe tačke su im zubi i kosti, pa da bi osigurali zdravlje tokom života moraju redovno ići na preglede ovih organa.\n\nProblem može nastati kada je jarac prinuđen da sa svojim saradnicima bude jako blizak. Teško mu pada da prihvata tuđe različitosti, pa u takvim situacijama ima potrebu da ljude kontroliše ili im nametne njegove tradicionalističke vrednosti. U njihovoj je prirodi da misle kako su jedini koji znaju da reše neki problem, ali moraju da nauče kako da oproste drugima, da im dozvole da budu ono što jesu i da prestanu da ih osuđuju. Najsrećniji su ako se tako ponašaju.', 'Lepa Lukić\nBranko Ćopić\nNađa Higl\nDobrica Ćosić\nMilovan Glišić\nJovan Sterija Popović\nŽarko Laušević', 'U poslednjih nekoliko dana, vaš primat je bila romantika i odnosi sa partnerom. Ako je u pitanju neko koga od skoro poznajete, nemojte se iznenaditi kada danas shvatite da vas ne vezuje ništa više osim strasti. Pokušajte da nađete odgovarajući način da nastavite u istom pravcu, pod uslovom da vam to odgovara. U suprotnom, ostaćete zarobljeni u odnosu koji vam ne prija.'),
(11, 'Vodolija', 'Vodolije se predstavljaju na dva načina: s jedne strane kao stidljivi i mirni, a sa druge strane mogu biti ekscentrični i energični. I u jednom i u drugom slučaju su duboki mislioci koji vole da pomažu drugim ljudima. Visoko intelektualan, ovo je znak vatrene nezavisnosti iz koje proizilazi intuicija praćena logikom. Oba tipa ličnosti veoma su sposobni da vide, bez predrasuda, obe strane, što ih čini osobama koje odlično rešavaju probleme. Iako su veoma prilagođeni energiji koja ih okružuje, vodolije imaju duboku potrebu da budu neko vreme sami i daleko od svega kako bi obnovili energiju. Ključna reč za ovaj znak je “mašta”. Osobe rođene u znaku vodolije mogu da vide svet pun mogućnosti iako se čini da ih nema.\n\nVodolija je vazdušni znak i kao takva koristi svoj um u svakoj prilici. Ako ne postoji mentalna stimulacija, njoj je dosadno i nedostaje joj motivacije da postigne najbolji rezultat.\n\nUran, vladajuća planeta Vodolije ima plahu, naglu i ponekad agresivnu prirodu, ali on takođe Vodolijama daje vizionarske kvalitete, one su u stanju da proniknu u budućnost i znaju tačno šta će raditi za pet ili deset godina. Uran im je podario moć brze i lake transformacije, pa su poznatije kao mislioci, progresivci i humanisti. Dobro se osećaju u grupi i zajdnici, pa teže da stalno budu okruženi drugim ljudima.\n\nVodolija je simbol čuvara vode, vode koja leči ljude, biljke i životinje i osigurava da se život nastavlja. Zato Vodolije teže da osete udeo u životnom ciklusu i u stanju su da urade bilo šta da bi se on održao.\n\nProblematični delovi tela za Vodoliju su zglobovi i cirkulacija. Za dobro zdravlje, najbolje bi bilo da redovno obavljaju preglede ovih organa.\n\nNajveći problem za Vodoliju predstavlja osećaj da je ograničena ili sputana. Zbog želje za slobodom i jednakosti za sve, uvek će težiti da osigura slobodu govora i kretanja kako joj odgovara. Vodolija ima reputaciju hladne i bezosećajne osobe, ali to je samo njen odbrambeni mehanizam protiv prerane bliskosti. Naučiti da veruju drugima i izražavanje emocija na zdrav način su dve veštine koje stiču rastom i razvojem tokom vremena.', 'Radomir Putnik\nLaza Kostić\nBranka Katić\nRadmila Savićević\nStefan Milenković\nIsidora Sekulić\nVlade Divac\nSava Šumanović\nRadoje Domanović', 'Jedan razgovor može da vas stavi u nezgodnu poziciju da morate da birate strane između porodice, prijatelja i vašeg partnera. Poslušajte vaše srce i ne dozvolite drugima da upravljaju vašim životom. Zdravstvena situacija zahteva vašu pažnju. Iako ne osećate nikakve simptome, došlo je vreme za jedan kompletan pregled organizma.'),
(12, 'Ribe', '„Razumevanje“ je najbolja reč koja opisuje pripadnike ovog znaka. Ribe kao druželjubive često se nađu u društvu veoma različitih ljudi. Njihova spremnost da daju sebe u emotivnom smislu uklapa se u celu sliku razumevanja drugih ljudi. Ribama je ugodno da budu podrška nekome. Pored toga što nisu predodređeni za vođe, njihovo prisustvo je važno u bilo kojoj stvari koje se prihvate.\n\nRibe su vodeni znak i kao takve odlikuju se empatičnošću i izraženim emocionalnim kapacitetom. Kao i rak i škorpija, osobe rođene u ovom znaku su često dublje nego ostali i teže da uzmu u obzir i neobjašnjive stvari koje život nosi kako bi se osećale srećno i ispunjeno.\n\nVladajuća planeta riba je Neptun koji upravlja snovima, psihom, metafizikom i kreativnošću. Zato su ribe intuitivnije i poseduju umetničke talente. Kako je Neptun povezan sa muzikom, ribe otkrivaju muzičke sklonosti u najranijim fazama života, ili ih usmeravaju ka poeziji.\n\nKako je riba simbol nekih religija i kako je povezana sa životnim ciklusom kao evolutivna osnova za razvoj kičmenjaka i ljudi. Ribe intuitivno imaju razumevanja za životne cikluse pa samim tim ostvaruju najbolju emotivnu vezu sa ostalim bićima.\n\nProbelmatične telesne oblasti za ribu su stopala i imuni sistem. Potrebno je stalno štititi stopala da ne bi došlo do težih povreda, a kako je imuni sistem neizmerno važan kao štit od svih bolesti, ne treba posebno isticati koliko je važno, naročito za Ribe da se pozabave svojim imunitetom.\n\nKada su previše pripojene drugima, ribe mogu onemogućiti ili opteretiti razvoj događaja. Iako je ovaj znak poznat po mudrosti neretko je da riba nekom prerano ili preterano veruje, pa se veliki broj puta razočara. Pod uticajem Urana, riba ponekad preduzima ulogu mučenika, čak svojevoljno, kako bi pridobila pažnju. Ukoliko nauči da postavi zdrave granice, riba će se osećati udobno u \"realnom\" svetu.', 'Sergej Ćetković\nMiroslav Mika Antić\nDejan Bodiroga\nOlivera Katarina\nŽelimir Željko Obradović\nVesna Trivalić\nJelena Janković\nProta Mateja Nenadović\nDragan Stojković Piksi', 'Prisustvovaćete jednom sastanku u krugu vaše porodice koji će voditi promenama u bliskoj budućnosti. U potpunosti mu se posvetite - ovo je ključni momenat da se zauzmete za vlastite stavove i izborite za neke nove uloge. Pažljivo slušajte šta drugi imaju da kažu i do kraja dana ne dozvolite da bilo ko utiče na vašu konačnu odluku.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `signs`
--
ALTER TABLE `signs`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
